openapi: 3.0.1
info:
  title: wallet-service
  version: '1.0'


servers:
  - url: 'http://localhost:3000'

paths:
  /api/v1/wallet/{id}:
    get:
      summary: Returns wallet info
      tags: [ "Wallet" ]
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Wallet id
      responses:
        '200':
          description: OK
